import fs from "node:fs/promises";
import path from "node:path";
import { createStore, type QMDStore } from "@tobilu/qmd";
import { resolveModelFile } from "node-llama-cpp";
import matter from "gray-matter";
import {
  type Config,
  DEFAULT_WIKI_EMBED_MODEL,
  DEFAULT_WIKI_GENERATE_MODEL,
  DEFAULT_WIKI_RERANK_MODEL,
} from "../../config.js";
import { modelsCachePath, wikiDbPath, wikiPath } from "../../utils/paths.js";
import type { PageFrontmatter, PageRecord } from "./types.js";

export const PAGES_DIR = "pages";
export const INDEX_FILE = "index.md";
export const LOG_FILE = "log.md";
export const SCHEMA_FILE = "schema.md";
export const DEFAULT_SEARCH_LIMIT = 5;
export const MAX_SEARCH_LIMIT = 20;
/** QMD collection name for wiki pages (fixed; not user-configurable). */
export const QMD_COLLECTION = "wiki";

function stripLeadingSlashes(value: string): string {
  return value.replace(/^[/\\]+/, "");
}

function firstSentence(value: string, maxLength: number = 180): string {
  const clean = value.replace(/\s+/g, " ").trim();
  if (!clean) {
    return "";
  }
  return clean.length > maxLength
    ? `${clean.slice(0, maxLength - 1).trimEnd()}…`
    : clean;
}

function safeString(value: unknown): string | null {
  return typeof value === "string" && value.trim().length > 0
    ? value.trim()
    : null;
}

function safeStringArray(value: unknown): string[] {
  if (!Array.isArray(value)) {
    return [];
  }
  return value
    .filter((item): item is string => typeof item === "string")
    .map((item) => item.trim())
    .filter((item) => item.length > 0);
}

function parseFrontmatter(content: string): {
  frontmatter: PageFrontmatter;
  body: string;
} {
  const parsed = matter(content);
  const data = parsed.data as Record<string, unknown>;
  return {
    frontmatter: {
      title: safeString(data.title) ?? undefined,
      summary: safeString(data.summary) ?? undefined,
      tags: safeStringArray(data.tags),
      related: safeStringArray(data.related),
      type: safeString(data.type) ?? undefined,
      created: safeString(data.created) ?? undefined,
      updated: safeString(data.updated) ?? undefined,
    },
    body: parsed.content.trim(),
  };
}

function wordCount(content: string): number {
  const words = content.trim().match(/\S+/g);
  return words ? words.length : 0;
}

function normalizeRelatedPath(value: string): string {
  let item = value.trim().replace(/\\/g, "/");
  item = item.replace(/^\[\[|\]\]$/g, "");
  item = stripLeadingSlashes(item);
  if (!item.endsWith(".md")) {
    item = `${item}.md`;
  }
  if (!item.startsWith(`${PAGES_DIR}/`)) {
    item = `${PAGES_DIR}/${item}`;
  }
  return item;
}

function deriveTitle(
  relativePath: string,
  frontmatter: PageFrontmatter,
): string {
  const fromFrontmatter = safeString(frontmatter.title);
  if (fromFrontmatter) {
    return fromFrontmatter;
  }
  return path.basename(relativePath, ".md").replace(/[-_]+/g, " ").trim();
}

function deriveSummary(
  frontmatter: PageFrontmatter,
  body: string,
  fallback: string,
): string {
  const fromFrontmatter = safeString(frontmatter.summary);
  if (fromFrontmatter) {
    return firstSentence(fromFrontmatter);
  }
  const bodySummary = firstSentence(body);
  return bodySummary || firstSentence(fallback) || "No summary available.";
}

function buildIndexMarkdown(pages: PageRecord[]): string {
  const sorted = [...pages].sort((a, b) => a.title.localeCompare(b.title));
  const lines: string[] = [
    "# Wiki Index",
    "",
    "<!-- Auto-generated by wiki_write_file. -->",
    "",
    `Updated: ${new Date().toISOString()}`,
    "",
    "## Pages",
  ];

  if (sorted.length === 0) {
    lines.push("- _No wiki pages yet._");
    return `${lines.join("\n")}\n`;
  }

  for (const page of sorted) {
    const tags = page.tags.length > 0 ? ` | tags: ${page.tags.join(", ")}` : "";
    lines.push(`- [${page.title}](${page.path}): ${page.summary}${tags}`);
  }

  return `${lines.join("\n")}\n`;
}

function buildLogEntry(
  operation: string,
  details: Record<string, string>,
): string {
  const lines: string[] = [
    `## [${new Date().toISOString()}] ${operation}`,
    ...Object.entries(details).map(([key, value]) => `- ${key}: ${value}`),
    "",
  ];
  return `${lines.join("\n")}\n`;
}

const DEFAULT_SCHEMA = `# Wiki Schema

This wiki is maintained by the agent through wiki tools.

## Structure
- \`pages/\`: markdown knowledge pages
- \`index.md\`: derived index (tool-managed)
- \`log.md\`: append-only activity log (tool-managed)

## Page conventions
- Use markdown files under \`pages/\`
- Prefer concise titles and summaries
- Add frontmatter when helpful (\`title\`, \`summary\`, \`tags\`, \`related\`, \`type\`)
- Use relative links to other pages when appropriate
`;

export class WikiStore {
  private static readonly instances = new Map<string, WikiStore>();

  private qmdStorePromise: Promise<QMDStore> | null = null;

  private constructor(
    _config: Config,
    public readonly root: string,
  ) {}

  /**
   * Shared instance per wiki root so warmup and tools reuse the same QMD store promise.
   */
  public static forConfig(config: Config): WikiStore {
    const root = wikiPath();
    let inst = WikiStore.instances.get(root);
    if (!inst) {
      inst = new WikiStore(config, root);
      WikiStore.instances.set(root, inst);
    }
    return inst;
  }

  public pageRelativePath(inputPath: string): string {
    const normalized = stripLeadingSlashes(
      inputPath.trim().replace(/\\/g, "/"),
    );
    if (!normalized) {
      throw new Error("Page path is required.");
    }
    const withPrefix = normalized.startsWith(`${PAGES_DIR}/`)
      ? normalized
      : `${PAGES_DIR}/${normalized}`;
    if (!withPrefix.toLowerCase().endsWith(".md")) {
      throw new Error("Page paths must end with .md");
    }
    return withPrefix;
  }

  public resolveWithin(relativePath: string): string {
    const abs = path.resolve(this.root, relativePath);
    const normalizedRoot = path.resolve(this.root);
    if (
      abs !== normalizedRoot &&
      !abs.startsWith(`${normalizedRoot}${path.sep}`) &&
      !(
        process.platform === "win32" &&
        abs
          .toLowerCase()
          .startsWith(`${normalizedRoot.toLowerCase()}${path.sep}`)
      )
    ) {
      throw new Error(`Path escapes wiki root: ${relativePath}`);
    }
    return abs;
  }

  public async pathExists(filePath: string): Promise<boolean> {
    try {
      await fs.access(filePath);
      return true;
    } catch {
      return false;
    }
  }

  public async ensureLayout(): Promise<void> {
    const pagesRoot = this.resolveWithin(PAGES_DIR);
    await fs.mkdir(pagesRoot, { recursive: true });

    const indexPath = this.resolveWithin(INDEX_FILE);
    const logPath = this.resolveWithin(LOG_FILE);
    const schemaPath = this.resolveWithin(SCHEMA_FILE);

    if (!(await this.pathExists(indexPath))) {
      await fs.writeFile(indexPath, buildIndexMarkdown([]), "utf8");
    }
    if (!(await this.pathExists(logPath))) {
      await fs.writeFile(logPath, "# Wiki Log\n\n", "utf8");
    }
    if (!(await this.pathExists(schemaPath))) {
      await fs.writeFile(schemaPath, `${DEFAULT_SCHEMA}\n`, "utf8");
    }
  }

  public async readPage(relativePath: string): Promise<PageRecord> {
    const absolutePath = this.resolveWithin(relativePath);
    const content = await fs.readFile(absolutePath, "utf8");
    const stat = await fs.stat(absolutePath);
    const parsed = parseFrontmatter(content);
    const title = deriveTitle(relativePath, parsed.frontmatter);
    const summary = deriveSummary(parsed.frontmatter, parsed.body, title);
    return {
      path: relativePath.replace(/\\/g, "/"),
      absolutePath,
      title,
      summary,
      tags: parsed.frontmatter.tags ?? [],
      related: (parsed.frontmatter.related ?? []).map(normalizeRelatedPath),
      type: parsed.frontmatter.type ?? null,
      created: parsed.frontmatter.created ?? null,
      updated: parsed.frontmatter.updated ?? null,
      wordCount: wordCount(parsed.body),
      mtime: stat.mtime.toISOString(),
      content,
      body: parsed.body,
      frontmatter: parsed.frontmatter,
    };
  }

  private async listPagePaths(): Promise<string[]> {
    const pagesRoot = this.resolveWithin(PAGES_DIR);
    const out: string[] = [];

    const walk = async (dirPath: string): Promise<void> => {
      const entries = await fs.readdir(dirPath, { withFileTypes: true });
      for (const entry of entries) {
        const fullPath = path.join(dirPath, entry.name);
        if (entry.isDirectory()) {
          await walk(fullPath);
          continue;
        }
        if (!entry.isFile() || !entry.name.toLowerCase().endsWith(".md")) {
          continue;
        }
        const relFromRoot = path
          .relative(this.root, fullPath)
          .replace(/\\/g, "/");
        out.push(relFromRoot);
      }
    };

    if (await this.pathExists(pagesRoot)) {
      await walk(pagesRoot);
    }

    out.sort((a, b) => a.localeCompare(b));
    return out;
  }

  public async listPages(): Promise<PageRecord[]> {
    const paths = await this.listPagePaths();
    return Promise.all(
      paths.map((relativePath) => this.readPage(relativePath)),
    );
  }

  public async writeIndex(pages: PageRecord[]): Promise<void> {
    const indexPath = this.resolveWithin(INDEX_FILE);
    await fs.writeFile(indexPath, buildIndexMarkdown(pages), "utf8");
  }

  public async appendLog(
    operation: string,
    details: Record<string, string>,
  ): Promise<void> {
    const logPath = this.resolveWithin(LOG_FILE);
    await fs.appendFile(logPath, buildLogEntry(operation, details), "utf8");
  }

  public async qmdStore(): Promise<QMDStore> {
    if (!this.qmdStorePromise) {
      this.qmdStorePromise = (async () => {
        await this.ensureLayout();
        const dbPath = wikiDbPath();
        await fs.mkdir(path.dirname(dbPath), { recursive: true });
        const pagesRoot = this.resolveWithin(PAGES_DIR);
        return createStore({
          dbPath,
          config: {
            collections: {
              [QMD_COLLECTION]: {
                path: pagesRoot,
                pattern: "**/*.md",
              },
            },
            models: {
              embed: DEFAULT_WIKI_EMBED_MODEL,
              rerank: DEFAULT_WIKI_RERANK_MODEL,
              generate: DEFAULT_WIKI_GENERATE_MODEL,
            },
          },
        });
      })();
    }
    return this.qmdStorePromise;
  }

  /**
   * Preload QMD models at startup (shared cache with LTM).
   */
  public async warmup(): Promise<void> {
    await this.ensureLayout();
    const models = [
      DEFAULT_WIKI_EMBED_MODEL,
      DEFAULT_WIKI_RERANK_MODEL,
      DEFAULT_WIKI_GENERATE_MODEL,
    ];
    const cacheDir = modelsCachePath();
    for (const model of new Set(models)) {
      await resolveModelFile(model, cacheDir);
    }
    await this.qmdStore();
  }

  public async syncSearchIndex(): Promise<void> {
    const store = await this.qmdStore();
    await store.update({ collections: [QMD_COLLECTION] });
    await store.embed({ force: false });
  }
}

export function create(config: Config): WikiStore {
  return WikiStore.forConfig(config);
}
