/**
 * Playful status labels shown while the agent is thinking, mirroring the
 * flavor of the CLI's `ThinkingStatus` component (see `src/chat/components/ThinkingStatus.tsx`).
 */
export const THINKING_VERBS = [
  "Thinking",
  "Analyzing contextual data",
  "Pondering",
  "Exploring possibilities",
  "Synthesizing ideas",
  "Computing paths",
  "Resolving logic",
  "Parsing semantics",
  "Constructing responses",
  "Interpreting intent",
  "Weaving thoughts",
  "Processing inputs",
  "Evaluating constraints",
  "Assembling paradigms",
  "Calibrating tensors",
  "Indexing memories",
  "Extrapolating vectors",
  "Connecting dots",
  "Deciphering queries",
  "Aligning objectives",
  "Routing thoughts",
  "Optimizing heuristic bounds",
  "Unrolling loops",
  "Querying knowledge graphs",
  "Bridging concepts",
  "Formulating strategies",
  "Reviewing context windows",
  "Distilling facts",
  "Structuring syntax",
  "Generating potential worlds",
  "Rendering concepts",
  "Simulating outcomes",
  "Drafting narratives",
  "Tracing execution flows",
  "Projecting scenarios",
  "Expanding context networks",
  "Cross-referencing archives",
  "Mapping algorithms",
  "Building semantic bridges",
  "Decoding symbols",
  "Unwinding recursive thoughts",
  "Fetching relevant insights",
  "Analyzing edge cases",
  "Establishing connections",
  "Evaluating syntax trees",
  "Navigating logical gates",
  "Deducing conclusions",
  "Searching the latent space",
  "Inferring implicit meaning",
  "Mapping dimensions",
  "Assessing probability",
  "Calculating next steps",
  "Traversing conceptual graphs",
  "Examining edge variables",
  "Verifying constraints",
  "Scanning mental databases",
  "Aggregating ideas",
  "Refining logic structures",
  "Analyzing potential solutions",
  "Calculating vector spaces",
  "Synthesizing paradigms",
  "Reviewing previous statements",
  "Mapping causal links",
  "Deriving corollaries",
  "Simulating dialogue",
  "Assembling puzzle pieces",
  "Generating possibilities",
  "Weighing alternatives",
  "Constructing arguments",
  "Decoding ambiguity",
  "Inferring patterns",
  "Clustering relevant topics",
  "Exploring latent variables",
  "Extracting semantic cores",
  "Balancing equations",
  "Translating concepts",
  "Modeling realities",
  "Connecting synapses",
  "Activating neural pathways",
  "Fine-tuning outputs",
  "Tracing linguistic roots",
  "Measuring semantic proximity",
  "Outlining next moves",
  "Constructing frameworks",
  "Organizing thought streams",
  "Linking references",
  "Analyzing tone",
  "Scanning knowledge bases",
  "Piecing together models",
  "Building cognitive structures",
  "Generating insights",
  "Forecasting responses",
  "Evaluating trade-offs",
  "Mapping inference paths",
  "Predicting user intent",
  "Resolving paradoxes",
  "Unpacking meaning",
  "Tracing references",
] as const;
